import { useState } from "react";
import { Sparkles, Loader2, CheckCircle2, XCircle } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { useLanguages } from "@/hooks/useAdmin";
import { supabase } from "@/integrations/supabase/client";

/**
 * AutoSeeder – calls the `seed-curriculum` edge function in repeated batches
 * to fill any lesson that currently has 0 questions with 3 AI-generated MCQs
 * grounded in the lesson's title + language.
 */
export function AutoSeeder() {
  const { toast } = useToast();
  const { data: languages = [] } = useLanguages();
  const [adminKey, setAdminKey] = useState("");
  const [languageSlug, setLanguageSlug] = useState("");
  const [batchSize, setBatchSize] = useState(15);
  const [running, setRunning] = useState(false);
  const [log, setLog] = useState([]);
  const [totals, setTotals] = useState({ ok: 0, fail: 0 });

  const appendLog = (entry) => setLog((prev) => [entry, ...prev].slice(0, 50));

  async function runOnce() {
    const { data, error } = await supabase.functions.invoke("seed-curriculum", {
      body: {
        adminKey,
        batchSize,
        languageSlug: languageSlug || undefined,
      },
    });
    if (error) throw error;
    return data;
  }

  async function start(continuous) {
    if (!adminKey) {
      toast({ title: "Admin key required", variant: "destructive" });
      return;
    }
    setRunning(true);
    setTotals({ ok: 0, fail: 0 });
    try {
      let iterations = 0;
      const maxIterations = continuous ? 80 : 1;
      while (iterations < maxIterations) {
        iterations++;
        const result = await runOnce();
        const ok = result?.succeeded ?? 0;
        const fail = result?.failed ?? 0;
        setTotals((t) => ({ ok: t.ok + ok, fail: t.fail + fail }));
        appendLog({
          time: new Date().toLocaleTimeString(),
          message: `Batch ${iterations}: ${ok} ok, ${fail} failed (processed ${result?.processed ?? 0})`,
          ok: fail === 0,
        });
        if ((result?.processed ?? 0) === 0) {
          appendLog({ time: new Date().toLocaleTimeString(), message: "All empty lessons filled 🎉", ok: true });
          break;
        }
      }
      toast({ title: "Seeding run complete" });
    } catch (e) {
      appendLog({ time: new Date().toLocaleTimeString(), message: e?.message || String(e), ok: false });
      toast({ title: "Seeding failed", description: e?.message, variant: "destructive" });
    } finally {
      setRunning(false);
    }
  }

  return (
    <div className="bg-slate-800 rounded-xl border border-slate-700 p-6 space-y-4">
      <div className="flex items-center gap-3">
        <Sparkles className="w-5 h-5 text-amber-400" />
        <h2 className="text-lg font-bold text-white">AI Curriculum Seeder</h2>
      </div>
      <p className="text-sm text-slate-400">
        Fills any lesson that has zero questions with 3 multiple-choice questions
        generated by the Lovable AI gateway, grounded in the lesson title and language.
        Uses open-source curriculum patterns (freeCodeCamp / MDN style) as the system prompt.
      </p>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-3">
        <div>
          <Label className="text-slate-300">Admin key</Label>
          <Input
            type="password"
            value={adminKey}
            onChange={(e) => setAdminKey(e.target.value)}
            placeholder="ADMIN_KEY"
            className="bg-slate-900 border-slate-700 text-white"
          />
        </div>
        <div>
          <Label className="text-slate-300">Language (optional)</Label>
          <Select value={languageSlug || "all"} onValueChange={(v) => setLanguageSlug(v === "all" ? "" : v)}>
            <SelectTrigger className="bg-slate-900 border-slate-700 text-white">
              <SelectValue placeholder="All languages" />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All languages</SelectItem>
              {languages.map((l) => (
                <SelectItem key={l.id} value={l.slug}>{l.name}</SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
        <div>
          <Label className="text-slate-300">Batch size (1–40)</Label>
          <Input
            type="number"
            min={1}
            max={40}
            value={batchSize}
            onChange={(e) => setBatchSize(Math.max(1, Math.min(40, Number(e.target.value) || 15)))}
            className="bg-slate-900 border-slate-700 text-white"
          />
        </div>
      </div>

      <div className="flex flex-wrap gap-3">
        <Button onClick={() => start(false)} disabled={running} className="bg-amber-600 hover:bg-amber-700">
          {running ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : <Sparkles className="w-4 h-4 mr-2" />}
          Run one batch
        </Button>
        <Button onClick={() => start(true)} disabled={running} variant="outline" className="border-amber-500 text-amber-400">
          {running ? <Loader2 className="w-4 h-4 mr-2 animate-spin" /> : null}
          Run continuously (until empty)
        </Button>
        <div className="ml-auto text-sm text-slate-300">
          Session totals: <span className="text-emerald-400 font-bold">{totals.ok} ok</span> ·{" "}
          <span className="text-red-400 font-bold">{totals.fail} failed</span>
        </div>
      </div>

      <div className="max-h-72 overflow-auto rounded-lg border border-slate-700 bg-slate-900 p-3 text-sm">
        {log.length === 0 ? (
          <p className="text-slate-500">No runs yet.</p>
        ) : log.map((entry, i) => (
          <div key={i} className="flex items-start gap-2 py-1">
            {entry.ok ? <CheckCircle2 className="w-4 h-4 text-emerald-400 mt-0.5" /> : <XCircle className="w-4 h-4 text-red-400 mt-0.5" />}
            <span className="text-slate-400">{entry.time}</span>
            <span className="text-slate-200">{entry.message}</span>
          </div>
        ))}
      </div>
    </div>
  );
}
